# ONIX Codelist 196 - EPUB Accessibility Feature Codes
CODELIST_196 = {
    '0': 'Accessibility summary',
    '1': 'LIA Compliance Scheme',
    '2': 'EPUB Accessibility Specification 1.0 A',
    '3': 'EPUB Accessibility Specification 1.0 AA',
    '4': 'EPUB Accessibility Specification 1.1',
    '5': 'PDF/UA',
    '8': 'Unknown accessibility',
    '9': 'Inaccessible, or known limited accessibility',
    '10': 'No reading system accessibility options actively disabled (except)',
    '11': 'Table of contents navigation',
    '12': 'Index navigation',
    '13': 'Single logical reading order',
    '14': 'Short alternative textual descriptions',
    '15': 'Full alternative textual descriptions',
    '16': 'Visualized data also available as non-graphical data',
    '17': 'Accessible math content as MathML',
    '18': 'Accessible chemistry content as ChemML',
    '19': 'Print-equivalent page numbering',
    '20': 'Synchronized pre-recorded audio',
    '21': 'Text-to-speech hinting provided',
    '22': 'Language tagging provided',
    '24': 'Dyslexia readability',
    '25': 'Use of color is not the sole means of conveying information',
    '26': 'Use of high contrast between text and background color',
    '27': 'Use of high contrast between foreground and background audio',
    '28': 'Full alternative audio descriptions',
    '29': 'Next/Previous structural navigation',
    '30': 'ARIA roles provided',
    '31': 'Accessible controls provided',
    '32': 'Landmark navigation',
    '34': 'Accessible chemistry content (as MathML)',
    '35': 'Accessible math content (as LaTeX)',
    '36': 'All textual content can be modified',
    '37': 'Use of ultra-high contrast between text foreground and background',
    '38': 'Unusual words or abbreviations explained',
    '39': 'Supplementary material to an audiobook is accessible',
    '40': 'Link purposes clear',
    '51': 'All non-decorative content supports reading via pre-recorded audio',
    '52': 'All non-decorative content supports reading without sight',
    '75': 'EEA Exception 1 – Micro-enterprises',
    '76': 'EAA exception 2 – Disproportionate burden',
    '77': 'EAA exception 3 – Fundamental modification',
    '80': 'WCAG v2.0',
    '81': 'WCAG v2.1',
    '82': 'WCAG v2.2',
    '84': 'WCAG level A',
    '85': 'WCAG level AA',
    '86': 'WCAG level AAA',
    '91': 'Latest accessibility assessment date',
    '92': 'Accessibility addendum',
    '93': 'Compliance certification by',
    '94': 'Compliance web page for detailed accessibility information',
    '95': 'Trusted intermediary\'s web page for detailed accessibility information',
    '96': 'Publisher\'s web page for detailed accessibility information',
    '97': 'Compatibility tested',
    '98': 'Trusted intermediary contact',
    '99': 'Publisher contact for further accessibility information'
}