"""Constants for ONIX processing"""

# ONIX namespaces
ONIX_30_NS = "http://ns.editeur.org/onix/3.0/reference"
NSMAP = {None: ONIX_30_NS}

# Default values
DEFAULT_NOTIFICATION_TYPE = "03"
DEFAULT_LANGUAGE_CODE = "eng"
DEFAULT_LANGUAGE_ROLE = "01"
DEFAULT_AUDIENCE_CODE_TYPE = "01"
DEFAULT_CONTENT_AUDIENCE = "00"
DEFAULT_PUBLISHER_ROLE = "01"
DEFAULT_SUPPLIER_ROLE = "01"
DEFAULT_PRODUCT_COMPOSITION = "00"
DEFAULT_PRODUCT_FORM = "EB"
DEFAULT_PRODUCT_FORM_DETAIL = "E101"