name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
    
    - name: Check dependencies
      run: |
        safety check -r requirements.txt
    
    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r app/ -ll -ii -s B311